import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { CountContext } from "~/contexts/CountContext";

const Home: NextPage = () => {
  let [count, setCount] = useState<number>(0)

  return (
    <>
      <Head>
        <title>T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CountContext.Provider value={{ count, setCount}}>
        <button onClick={() => setCount(count++)} className="m-3 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-lg hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80">
          Increment Count
        </button>
        {count}
        <button onClick={() => setCount(count--)} className="m-3 px-6 py-2 font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-600 rounded-lg hover:bg-blue-500 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-80">
          Decrement Count
        </button>
        {count > 0 ? <p>Count is Positive</p> : count < 0 ? <p>Count is Negative</p>: count === 0 ? <p>Count is Zero</p> : null}
      </CountContext.Provider>
    </>
  );
};

export default Home;
